version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    # depends_on:
      # - backend
      # - frontend

  # backend:
  #   image: your-backend-image:latest
  #   ports:
  #     - "8080:8080"

  # frontend:
  #   image: your-frontend-image:latest
  #   ports:
  #     - "3000:3000"
